sonar.projectKey=fga-eps-mds_2026-2-AnatoQuizUp-Usuario-Service
sonar.organization=fga-eps-mds-1

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/migrations/**,**/seeds/**,**/*.config.js,**/*.config.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*.test.*,**/*.spec.*,**/index.*,**/server.*,**/app.*,**/migrations/**,**/seeds/**,**/*.config.*,**/*.routes.ts,**/*.constants.ts,src/scripts/**,src/shared/constants/**,src/shared/types/**,src/shared/errors/**,src/modules/exemplo/**,src/config/db.ts,src/config/logger.ts,src/shared/middlewares/papeis.middleware.ts,src/shared/middlewares/tratamento-erros.middleware.ts

sonar.sourceEncoding=UTF-8
